/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "dd-daemon.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.dd.service
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:ComDdService
 * @title: ComDdService
 * @short_description: Generated C code for the com.dd.service D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.dd.service ---- */

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_ioctl_IN_ARG_iocmd =
{
  {
    -1,
    (gchar *) "iocmd",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_ioctl_IN_ARG_pin =
{
  {
    -1,
    (gchar *) "pin",
    (gchar *) "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_ioctl_IN_ARG_uin =
{
  {
    -1,
    (gchar *) "uin",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_ioctl_IN_ARG_uout =
{
  {
    -1,
    (gchar *) "uout",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_dd_service_method_info_ioctl_IN_ARG_pointers[] =
{
  &_com_dd_service_method_info_ioctl_IN_ARG_iocmd,
  &_com_dd_service_method_info_ioctl_IN_ARG_pin,
  &_com_dd_service_method_info_ioctl_IN_ARG_uin,
  &_com_dd_service_method_info_ioctl_IN_ARG_uout,
  NULL
};

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_ioctl_OUT_ARG_pout =
{
  {
    -1,
    (gchar *) "pout",
    (gchar *) "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo * const _com_dd_service_method_info_ioctl_OUT_ARG_pointers[] =
{
  &_com_dd_service_method_info_ioctl_OUT_ARG_pout,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_dd_service_method_info_ioctl =
{
  {
    -1,
    (gchar *) "ioctl",
    (GDBusArgInfo **) &_com_dd_service_method_info_ioctl_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_dd_service_method_info_ioctl_OUT_ARG_pointers,
    NULL
  },
  "handle-ioctl",
  FALSE
};

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_test_IN_ARG_pin =
{
  {
    -1,
    (gchar *) "pin",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_dd_service_method_info_test_IN_ARG_pointers[] =
{
  &_com_dd_service_method_info_test_IN_ARG_pin,
  NULL
};

static const _ExtendedGDBusArgInfo _com_dd_service_method_info_test_OUT_ARG_pout =
{
  {
    -1,
    (gchar *) "pout",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_dd_service_method_info_test_OUT_ARG_pointers[] =
{
  &_com_dd_service_method_info_test_OUT_ARG_pout,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_dd_service_method_info_test =
{
  {
    -1,
    (gchar *) "test",
    (GDBusArgInfo **) &_com_dd_service_method_info_test_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_dd_service_method_info_test_OUT_ARG_pointers,
    NULL
  },
  "handle-test",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _com_dd_service_method_info_pointers[] =
{
  &_com_dd_service_method_info_ioctl,
  &_com_dd_service_method_info_test,
  NULL
};

static const _ExtendedGDBusArgInfo _com_dd_service_signal_info_notification_ARG_data =
{
  {
    -1,
    (gchar *) "data",
    (gchar *) "ay",
    NULL
  },
  TRUE
};

static const _ExtendedGDBusArgInfo * const _com_dd_service_signal_info_notification_ARG_pointers[] =
{
  &_com_dd_service_signal_info_notification_ARG_data,
  NULL
};

static const _ExtendedGDBusSignalInfo _com_dd_service_signal_info_notification =
{
  {
    -1,
    (gchar *) "notification",
    (GDBusArgInfo **) &_com_dd_service_signal_info_notification_ARG_pointers,
    NULL
  },
  "notification"
};

static const _ExtendedGDBusArgInfo _com_dd_service_signal_info_test_ARG_data =
{
  {
    -1,
    (gchar *) "data",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_dd_service_signal_info_test_ARG_pointers[] =
{
  &_com_dd_service_signal_info_test_ARG_data,
  NULL
};

static const _ExtendedGDBusSignalInfo _com_dd_service_signal_info_test =
{
  {
    -1,
    (gchar *) "test",
    (GDBusArgInfo **) &_com_dd_service_signal_info_test_ARG_pointers,
    NULL
  },
  "test"
};

static const _ExtendedGDBusSignalInfo * const _com_dd_service_signal_info_pointers[] =
{
  &_com_dd_service_signal_info_notification,
  &_com_dd_service_signal_info_test,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _com_dd_service_interface_info =
{
  {
    -1,
    (gchar *) "com.dd.service",
    (GDBusMethodInfo **) &_com_dd_service_method_info_pointers,
    (GDBusSignalInfo **) &_com_dd_service_signal_info_pointers,
    NULL,
    NULL
  },
  "com-dd-service",
};


/**
 * com_dd_service_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
com_dd_service_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_com_dd_service_interface_info.parent_struct;
}

/**
 * com_dd_service_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #ComDdService interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
com_dd_service_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * ComDdService:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link>.
 */

/**
 * ComDdServiceIface:
 * @parent_iface: The parent interface.
 * @handle_ioctl: Handler for the #ComDdService::handle-ioctl signal.
 * @handle_test: Handler for the #ComDdService::handle-test signal.
 * @notification: Handler for the #ComDdService::notification signal.
 * @test: Handler for the #ComDdService::test signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link>.
 */

typedef ComDdServiceIface ComDdServiceInterface;
G_DEFINE_INTERFACE (ComDdService, com_dd_service, G_TYPE_OBJECT);

static void
com_dd_service_default_init (ComDdServiceIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * ComDdService::handle-ioctl:
   * @object: A #ComDdService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_iocmd: Argument passed by remote caller.
   * @arg_pin: Argument passed by remote caller.
   * @arg_uin: Argument passed by remote caller.
   * @arg_uout: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-dd-service.ioctl">ioctl()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_dd_service_complete_ioctl() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-ioctl",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComDdServiceIface, handle_ioctl),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT, G_TYPE_VARIANT, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * ComDdService::handle-test:
   * @object: A #ComDdService.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_pin: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-dd-service.test">test()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_dd_service_complete_test() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-test",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComDdServiceIface, handle_test),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT);

  /* GObject signals for received D-Bus signals: */
  /**
   * ComDdService::notification:
   * @object: A #ComDdService.
   * @arg_data: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-dd-service.notification">"notification"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("notification",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComDdServiceIface, notification),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  /**
   * ComDdService::test:
   * @object: A #ComDdService.
   * @arg_data: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-dd-service.test">"test"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("test",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComDdServiceIface, test),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_INT);

}

/**
 * com_dd_service_emit_notification:
 * @object: A #ComDdService.
 * @arg_data: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-dd-service.notification">"notification"</link> D-Bus signal.
 */
void
com_dd_service_emit_notification (
    ComDdService *object,
    GVariant *arg_data)
{
  g_signal_emit_by_name (object, "notification", arg_data);
}

/**
 * com_dd_service_emit_test:
 * @object: A #ComDdService.
 * @arg_data: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-dd-service.test">"test"</link> D-Bus signal.
 */
void
com_dd_service_emit_test (
    ComDdService *object,
    gint arg_data)
{
  g_signal_emit_by_name (object, "test", arg_data);
}

/**
 * com_dd_service_call_ioctl:
 * @proxy: A #ComDdServiceProxy.
 * @arg_iocmd: Argument to pass with the method invocation.
 * @arg_pin: Argument to pass with the method invocation.
 * @arg_uin: Argument to pass with the method invocation.
 * @arg_uout: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-dd-service.ioctl">ioctl()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_dd_service_call_ioctl_finish() to get the result of the operation.
 *
 * See com_dd_service_call_ioctl_sync() for the synchronous, blocking version of this method.
 */
void
com_dd_service_call_ioctl (
    ComDdService *proxy,
    guint arg_iocmd,
    GVariant *arg_pin,
    guint arg_uin,
    guint arg_uout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ioctl",
    g_variant_new ("(u@ayuu)",
                   arg_iocmd,
                   arg_pin,
                   arg_uin,
                   arg_uout),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_dd_service_call_ioctl_finish:
 * @proxy: A #ComDdServiceProxy.
 * @out_pout: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_dd_service_call_ioctl().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_dd_service_call_ioctl().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_dd_service_call_ioctl_finish (
    ComDdService *proxy,
    GVariant **out_pout,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@ay)",
                 out_pout);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_dd_service_call_ioctl_sync:
 * @proxy: A #ComDdServiceProxy.
 * @arg_iocmd: Argument to pass with the method invocation.
 * @arg_pin: Argument to pass with the method invocation.
 * @arg_uin: Argument to pass with the method invocation.
 * @arg_uout: Argument to pass with the method invocation.
 * @out_pout: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-dd-service.ioctl">ioctl()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_dd_service_call_ioctl() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_dd_service_call_ioctl_sync (
    ComDdService *proxy,
    guint arg_iocmd,
    GVariant *arg_pin,
    guint arg_uin,
    guint arg_uout,
    GVariant **out_pout,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ioctl",
    g_variant_new ("(u@ayuu)",
                   arg_iocmd,
                   arg_pin,
                   arg_uin,
                   arg_uout),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@ay)",
                 out_pout);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_dd_service_call_test:
 * @proxy: A #ComDdServiceProxy.
 * @arg_pin: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-dd-service.test">test()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_dd_service_call_test_finish() to get the result of the operation.
 *
 * See com_dd_service_call_test_sync() for the synchronous, blocking version of this method.
 */
void
com_dd_service_call_test (
    ComDdService *proxy,
    gint arg_pin,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "test",
    g_variant_new ("(i)",
                   arg_pin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_dd_service_call_test_finish:
 * @proxy: A #ComDdServiceProxy.
 * @out_pout: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_dd_service_call_test().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_dd_service_call_test().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_dd_service_call_test_finish (
    ComDdService *proxy,
    gint *out_pout,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_pout);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_dd_service_call_test_sync:
 * @proxy: A #ComDdServiceProxy.
 * @arg_pin: Argument to pass with the method invocation.
 * @out_pout: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-dd-service.test">test()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_dd_service_call_test() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_dd_service_call_test_sync (
    ComDdService *proxy,
    gint arg_pin,
    gint *out_pout,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "test",
    g_variant_new ("(i)",
                   arg_pin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_pout);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_dd_service_complete_ioctl:
 * @object: A #ComDdService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @pout: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-dd-service.ioctl">ioctl()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_dd_service_complete_ioctl (
    ComDdService *object,
    GDBusMethodInvocation *invocation,
    GVariant *pout)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@ay)",
                   pout));
}

/**
 * com_dd_service_complete_test:
 * @object: A #ComDdService.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @pout: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-dd-service.test">test()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_dd_service_complete_test (
    ComDdService *object,
    GDBusMethodInvocation *invocation,
    gint pout)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   pout));
}

/* ------------------------------------------------------------------------ */

/**
 * ComDdServiceProxy:
 *
 * The #ComDdServiceProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ComDdServiceProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ComDdServiceProxy.
 */

struct _ComDdServiceProxyPrivate
{
  GData *qdata;
};

static void com_dd_service_proxy_iface_init (ComDdServiceIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (ComDdServiceProxy, com_dd_service_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (ComDdServiceProxy)
                         G_IMPLEMENT_INTERFACE (TYPE_COM_DD_SERVICE, com_dd_service_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (ComDdServiceProxy, com_dd_service_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_COM_DD_SERVICE, com_dd_service_proxy_iface_init));

#endif
static void
com_dd_service_proxy_finalize (GObject *object)
{
  ComDdServiceProxy *proxy = COM_DD_SERVICE_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (com_dd_service_proxy_parent_class)->finalize (object);
}

static void
com_dd_service_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
com_dd_service_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
com_dd_service_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_com_dd_service_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_COM_DD_SERVICE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_COM_DD_SERVICE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
com_dd_service_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  ComDdServiceProxy *proxy = COM_DD_SERVICE_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_dd_service_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_dd_service_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
com_dd_service_proxy_init (ComDdServiceProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = com_dd_service_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_COM_DD_SERVICE_PROXY, ComDdServiceProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), com_dd_service_interface_info ());
}

static void
com_dd_service_proxy_class_init (ComDdServiceProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = com_dd_service_proxy_finalize;
  gobject_class->get_property = com_dd_service_proxy_get_property;
  gobject_class->set_property = com_dd_service_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = com_dd_service_proxy_g_signal;
  proxy_class->g_properties_changed = com_dd_service_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (ComDdServiceProxyPrivate));
#endif
}

static void
com_dd_service_proxy_iface_init (ComDdServiceIface *iface)
{
}

/**
 * com_dd_service_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_dd_service_proxy_new_finish() to get the result of the operation.
 *
 * See com_dd_service_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
com_dd_service_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_COM_DD_SERVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.dd.service", NULL);
}

/**
 * com_dd_service_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_dd_service_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with com_dd_service_proxy_new().
 *
 * Returns: (transfer full) (type ComDdServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
ComDdService *
com_dd_service_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return COM_DD_SERVICE (ret);
  else
    return NULL;
}

/**
 * com_dd_service_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See com_dd_service_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ComDdServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
ComDdService *
com_dd_service_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_COM_DD_SERVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.dd.service", NULL);
  if (ret != NULL)
    return COM_DD_SERVICE (ret);
  else
    return NULL;
}


/**
 * com_dd_service_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like com_dd_service_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_dd_service_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See com_dd_service_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
com_dd_service_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_COM_DD_SERVICE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.dd.service", NULL);
}

/**
 * com_dd_service_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_dd_service_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with com_dd_service_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type ComDdServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
ComDdService *
com_dd_service_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return COM_DD_SERVICE (ret);
  else
    return NULL;
}

/**
 * com_dd_service_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like com_dd_service_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See com_dd_service_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ComDdServiceProxy): The constructed proxy object or %NULL if @error is set.
 */
ComDdService *
com_dd_service_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_COM_DD_SERVICE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.dd.service", NULL);
  if (ret != NULL)
    return COM_DD_SERVICE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * ComDdServiceSkeleton:
 *
 * The #ComDdServiceSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ComDdServiceSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ComDdServiceSkeleton.
 */

struct _ComDdServiceSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_com_dd_service_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_COM_DD_SERVICE);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_COM_DD_SERVICE);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_com_dd_service_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_dd_service_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_com_dd_service_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_dd_service_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _com_dd_service_skeleton_vtable =
{
  _com_dd_service_skeleton_handle_method_call,
  _com_dd_service_skeleton_handle_get_property,
  _com_dd_service_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
com_dd_service_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return com_dd_service_interface_info ();
}

static GDBusInterfaceVTable *
com_dd_service_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_com_dd_service_skeleton_vtable;
}

static GVariant *
com_dd_service_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_com_dd_service_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _com_dd_service_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _com_dd_service_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _com_dd_service_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.dd.service", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
com_dd_service_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_com_dd_service_on_signal_notification (
    ComDdService *object,
    GVariant *arg_data)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(@ay)",
                   arg_data));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.dd.service", "notification",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_com_dd_service_on_signal_test (
    ComDdService *object,
    gint arg_data)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(i)",
                   arg_data));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.dd.service", "test",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void com_dd_service_skeleton_iface_init (ComDdServiceIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (ComDdServiceSkeleton, com_dd_service_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (ComDdServiceSkeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_COM_DD_SERVICE, com_dd_service_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (ComDdServiceSkeleton, com_dd_service_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_COM_DD_SERVICE, com_dd_service_skeleton_iface_init));

#endif
static void
com_dd_service_skeleton_finalize (GObject *object)
{
  ComDdServiceSkeleton *skeleton = COM_DD_SERVICE_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (com_dd_service_skeleton_parent_class)->finalize (object);
}

static void
com_dd_service_skeleton_init (ComDdServiceSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = com_dd_service_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_COM_DD_SERVICE_SKELETON, ComDdServiceSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
com_dd_service_skeleton_class_init (ComDdServiceSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = com_dd_service_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = com_dd_service_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = com_dd_service_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = com_dd_service_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = com_dd_service_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (ComDdServiceSkeletonPrivate));
#endif
}

static void
com_dd_service_skeleton_iface_init (ComDdServiceIface *iface)
{
  iface->notification = _com_dd_service_on_signal_notification;
  iface->test = _com_dd_service_on_signal_test;
}

/**
 * com_dd_service_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-dd-service.top_of_page">com.dd.service</link>.
 *
 * Returns: (transfer full) (type ComDdServiceSkeleton): The skeleton object.
 */
ComDdService *
com_dd_service_skeleton_new (void)
{
  return COM_DD_SERVICE (g_object_new (TYPE_COM_DD_SERVICE_SKELETON, NULL));
}

